Repository bridge-core/bridge., pull requests merged in 2019-09, with the labels that each got.

#50 [Feature] bridge. Core
  plugin_docs/auto_completions/dynamic_references.md
  src/renderer/components/sidebar/content/Plugins.vue
  src/renderer/scripts/FileSystem.js
  src/renderer/scripts/TabSystem.js
  src/renderer/scripts/autoCompletions/Dynamic.js
  src/renderer/scripts/autoCompletions/Provider.js
  src/renderer/scripts/constants.js
  src/renderer/scripts/files/AnimationController.js
  src/renderer/scripts/files/Manifest.js
  src/renderer/scripts/plugins/PluginLoader.js
  src/renderer/scripts/plugins/bridgeCore/EntityHandler.js
  src/renderer/scripts/plugins/bridgeCore/main.js
  src/renderer/scripts/utilities/useAttr.js
  src/renderer/windows/CreateProject.js
  static/auto_completions/entity/main.json
  static/auto_completions/entity/main_beta.json
Labels: Feature

#15 fix for linux/macOS (almost)
  package.json
  src/main/communicator.js
  src/main/index.js
  src/renderer/components/sidebar/content/explorer/Toolbar.vue
  src/renderer/scripts/FileSystem.js
  src/renderer/scripts/TemplateSets.js
  src/renderer/scripts/constants.js
  src/renderer/scripts/editor/FileType.js
  src/renderer/scripts/editor/OmegaCache.js
  src/renderer/scripts/editor/VersionMap.js
  src/renderer/scripts/editor/problems/components.js
  src/renderer/scripts/utilities/BridgeStore.js
  src/renderer/store/Settings.js
  src/renderer/windows/TemplateSets.js
  src/shared/Paths.js
Labels: Bug, Feature, Next Version

#79 Implement custom themes
  README.md
  plugin_docs/json/themes.md
  plugin_docs/main.md
  src/renderer/App.vue
  src/renderer/components/AppMenu.vue
  src/renderer/components/AppToolbar.vue
  src/renderer/components/context_menu/Main.vue
  src/renderer/components/documentation/Main.vue
  src/renderer/components/editor_shell/FileManager.vue
  src/renderer/components/editor_shell/JsonEditor/HighlightAttribute.vue
  src/renderer/components/editor_shell/JsonEditor/HighlightText.vue
  src/renderer/components/editor_shell/JsonEditor/HoverCard.vue
  src/renderer/components/editor_shell/JsonEditor/PredictingInput.vue
  src/renderer/components/editor_shell/TabSystem.vue
  src/renderer/components/editor_shell/TextAutoCompletions.vue
  src/renderer/components/plugin_install/CloudPlugin.vue
  src/renderer/components/plugin_install/Main.vue
  src/renderer/components/plugin_install/PluginList.vue
  src/renderer/components/plugin_install/WebPlugins.vue
  src/renderer/components/sidebar/Main.vue
  src/renderer/components/sidebar/Navigation.vue
  src/renderer/components/sidebar/content/Custom.vue
  src/renderer/components/sidebar/content/Explorer.vue
  src/renderer/components/sidebar/content/Plugins.vue
  src/renderer/components/sidebar/content/explorer/NoProjects.vue
  src/renderer/components/sidebar/content/explorer/RpToolbar.vue
  src/renderer/components/sidebar/content/explorer/Toolbar.vue
  src/renderer/components/windowFactory/SidebarElement.vue
  src/renderer/components/windowFactory/ToolbarElement.vue
  src/renderer/components/windowFactory/Window.vue
  src/renderer/components/windowFactory/WindowContent.vue
  src/renderer/main.js
  src/renderer/scripts/ProjectConfig.js
  src/renderer/scripts/editor/ThemeManager.js
  src/renderer/scripts/plugins/PluginLoader.js
  src/renderer/store/Settings.js
  src/renderer/store/modules/Appearance.js
  src/renderer/store/modules/Plugins.js
  src/renderer/windows/EditMoLang.js
  src/renderer/windows/Settings.js
  static/data/cm_name_map.json
  static/themes/classic.json
  static/themes/coral.json
  static/themes/deep_blue.json
  static/themes/default.json
  static/themes/orange.json
Labels: Feature, Next Version
